In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [3]:
DATA_PATH = "../data/raw/SuperStoreOrders.csv"

df = pd.read_csv(DATA_PATH)

print(f"Dataset Shape : {df.shape}")

df.head()

Dataset Shape : (51290, 21)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,OFF-PA-10001492,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,FUR-FU-10003447,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [4]:
print("="*60)
print("DATASET INFORMATION")
print("="*60)

df.info()

============================================================
DATASET INFORMATION
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), str(16)
memory usage: 8.2 MB

In [5]:
# BASIC STATS
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

print("\nColumn Names\n")
print(df.columns.tolist())

Rows : 51290
Columns : 21

Column Names

['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name', 'segment', 'state', 'country', 'market', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit', 'shipping_cost', 'order_priority', 'year']

In [6]:
# MISSING VALUES 

missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean()*100,2)
})

missing.sort_values("Missing Values", ascending=False)

                Missing Values  Percentage
order_id                     0         0.0
order_date                   0         0.0
ship_date                    0         0.0
ship_mode                    0         0.0
customer_name                0         0.0
segment                      0         0.0
state                        0         0.0
country                      0         0.0
market                       0         0.0
region                       0         0.0
product_id                   0         0.0
category                     0         0.0
sub_category                 0         0.0
product_name                 0         0.0
sales                        0         0.0
quantity                     0         0.0
discount                     0         0.0
profit                       0         0.0
shipping_cost                0         0.0
order_priority               0         0.0
year                         0         0.0

In [7]:
# DUPLICATE RECORDS

duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 0

In [8]:
# UNIQUE VALUES

unique = pd.DataFrame({
    "Unique Values": df.nunique()
})

unique

                Unique Values
order_id                25035
order_date               1430
ship_date                1464
ship_mode                   4
customer_name             795
segment                     3
state                    1094
country                   147
market                      7
region                     13
product_id              10292
category                    3
sub_category               17
product_name             3788
sales                    2246
quantity                   14
discount                   27
profit                  24575
shipping_cost           10037
order_priority              4
year                        4

In [9]:
# NUMERICAL STATS

numeric_summary = df.describe().transpose()

In [10]:
# COVERTING DATE COLUMNS TO DATETIME FORMAT FOR ANALYSIS 

# Date columns

df["order_date"] = pd.to_datetime(df["order_date"], format='%d/%m/%Y', errors='coerce')

df["ship_date"] = pd.to_datetime(df["ship_date"], format='%d/%m/%Y', errors='coerce')

# Numeric columns

df["sales"] = pd.to_numeric(df["sales"], errors="coerce")

In [11]:
df.dtypes

order_id                     str
order_date        datetime64[us]
ship_date         datetime64[us]
ship_mode                    str
customer_name                str
segment                      str
state                        str
country                      str
market                       str
region                       str
product_id                   str
category                     str
sub_category                 str
product_name                 str
sales                    float64
quantity                   int64
discount                 float64
profit                   float64
shipping_cost            float64
order_priority               str
year                       int64
dtype: object

In [12]:
# NUMERICAL SUMMARY

df.describe().T

,count,mean,min,25%,50%,75%,max,std
order_date,20067,2013-05-02 23:06:58.179100,2011-01-01 00:00:00,2012-06-08 00:00:00,2013-07-02 00:00:00,2014-05-11 00:00:00,2014-12-12 00:00:00,NaN
ship_date,19834,2013-05-10 01:01:29.664213,2011-01-03 00:00:00,2012-06-11 00:00:00,2013-07-04 00:00:00,2014-06-01 00:00:00,2015-01-07 00:00:00,NaN
sales,48660.0,161.017838,0.0,29.0,77.0,208.0,999.0,201.092519
quantity,51290.0,3.476545,1.0,2.0,3.0,5.0,14.0,2.278766
discount,51290.0,0.142908,0.0,0.0,0.0,0.2,0.85,0.21228
profit,51290.0,28.64174,-6599.978,0.0,9.24,36.81,8399.976,174.424113
shipping_cost,51290.0,26.375915,0.0,2.61,7.79,24.45,933.57,57.296804
year,51290.0,2012.777208,2011.0,2012.0,2013.0,2014.0,2014.0,1.098931

In [13]:
# CATEGORICAL SUMMARY 

categorical = df.select_dtypes(include="object")

categorical.describe().T

C:\Users\Admin\AppData\Local\Temp\ipykernel_22852\1799867964.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical = df.select_dtypes(include="object")

                count unique              top   freq
order_id        51290  25035   CA-2014-100111     14
ship_mode       51290      4   Standard Class  30775
customer_name   51290    795  Muhammed Yedwab    108
segment         51290      3         Consumer  26518
state           51290   1094       California   2001
country         51290    147    United States   9994
market          51290      7             APAC  11002
region          51290     13          Central  11117
product_id      51290  10292  OFF-AR-10003651     35
category        51290      3  Office Supplies  31273
sub_category    51290     17          Binders   6152
product_name    51290   3788          Staples    227
order_priority  51290      4           Medium  29433

In [14]:
# DATE ANALYSIS

print("Order Date Range")

print(df["order_date"].min())

print(df["order_date"].max())

print()

print("Ship Date Range")

print(df["ship_date"].min())

print(df["ship_date"].max())

Order Date Range
2011-01-01 00:00:00
2014-12-12 00:00:00

Ship Date Range
2011-01-03 00:00:00
2015-01-07 00:00:00

In [15]:
# CUSTOMER ANALYSIS

print("Unique Customers :", df["customer_name"].nunique())

print("Unique Orders :", df["order_id"].nunique())

print("Unique Products :", df["product_id"].nunique())

Unique Customers : 795
Unique Orders : 25035
Unique Products : 10292

In [16]:
# REGION DISTRIBUTION

df["region"].value_counts().to_frame("Customers")

                Customers
region
Central             11117
South                6645
EMEA                 5029
North                4785
Africa               4587
Oceania              3487
West                 3203
Southeast Asia       3129
East                 2848
North Asia           2338
Central Asia         2048
Caribbean            1690
Canada                384

In [17]:
# MARKET DISTRIBUTION

df["market"].value_counts().to_frame("Orders")

        Orders
market
APAC     11002
LATAM    10294
EU       10000
US        9994
EMEA      5029
Africa    4587
Canada     384

In [18]:
# SEGMENT DISTRIBUTION

df["segment"].value_counts().to_frame("Customers")

             Customers
segment
Consumer         26518
Corporate        15429
Home Office       9343

In [19]:
# TOP CUSTOMERS BY ORDER COUNT

(
    df.groupby("customer_name")["order_id"]
      .count()
      .sort_values(ascending=False)
      .head(10)
      .to_frame("Orders")
)

                     Orders
customer_name
Muhammed Yedwab         108
Steven Ward             106
Patrick O'Brill         102
Gary Hwang              102
Bill Eplett             102
Harry Greene            101
Eric Murdock            100
Art Ferguson             98
Brosina Hoffman          97
Chloris Kastensmidt      96

In [20]:
# TOP CUSTOMERS BY REVENUE

(
    df.groupby("customer_name")["sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
      .to_frame("Revenue")

)

                  Revenue
customer_name
Eric Murdock      19489.0
John Grady        19483.0
Maria Etezadi     18237.0
Theone Pippenger  17416.0
Dan Reichenbach   16705.0
Ben Ferrer        16661.0
Randy Bradley     16399.0
Mathew Reese      16125.0
Muhammed Yedwab   16091.0
Steven Ward       15984.0

In [21]:
# SALES DISTRIBUTION

df["sales"].describe()

count    48660.000000
mean       161.017838
std        201.092519
min          0.000000
25%         29.000000
50%         77.000000
75%        208.000000
max        999.000000
Name: sales, dtype: float64

In [22]:
# PROFIT ANALYSIS

print("Negative Profit Orders")

(df["profit"] < 0).sum()

Negative Profit Orders

np.int64(12543)

In [23]:
# DISCOUNT ANALYSIS

df["discount"].value_counts().sort_index()

discount
0.000    29009
0.002      461
0.070      150
0.100     4068
0.150      541
0.170      735
0.200     4998
0.202       41
0.250      198
0.270      388
0.300      340
0.320       27
0.350      122
0.370       74
0.400     3177
0.402      104
0.450      327
0.470      725
0.500     1633
0.550       10
0.570       12
0.600     2006
0.602       23
0.650       17
0.700     1786
0.800      316
0.850        2
Name: count, dtype: int64

In [24]:
# SHIPPING ANALYSIS
df["ship_mode"].value_counts()

ship_mode
Standard Class    30775
Second Class      10309
First Class        7505
Same Day           2701
Name: count, dtype: int64

In [25]:
# DATA QUALITY CHCEKS

print("="*60)
print("DATA QUALITY CHECKS")
print("="*60)

print("Null Values :", df.isnull().sum().sum())

print("Duplicate Rows :", df.duplicated().sum())

print("Negative Sales :", (df["sales"] < 0).sum())

print("Negative Profit :", (df["profit"] < 0).sum())

print("Future Dates :", (df["order_date"] > pd.Timestamp.today()).sum())

============================================================
DATA QUALITY CHECKS
============================================================
Null Values : 65309
Duplicate Rows : 0
Negative Sales : 0
Negative Profit : 12543
Future Dates : 0

In [26]:
# SUMMARY


summary = {
    "Total Orders": df["order_id"].nunique(),
    "Total Customers": df["customer_name"].nunique(),
    "Total Products": df["product_id"].nunique(),
    "Total Revenue": round(df["sales"].sum(),2),
    "Average Order Value": round(df["sales"].mean(),2),
    "Average Profit": round(df["profit"].mean(),2),
}

pd.DataFrame(summary.items(), columns=["Metric","Value"])

                Metric       Value
0         Total Orders    25035.00
1      Total Customers      795.00
2       Total Products    10292.00
3        Total Revenue  7835128.00
4  Average Order Value      161.02
5       Average Profit       28.64